#lang aws-lambda-serverless
service: www-tojo-tokyo

provider:
  name: aws
  runtime: provided
  region: ap-northeast-1
  memorySize: 256
  timeout: 1
  resourcePolicy:
    - Effect: Allow
      Principal: "*"
      Action: execute-api:Invoke
      Resource:
        - execute-api:/*/*/*
      Condition:
        IpAddress:
          aws:SourceIp: ${self:custom.sourceIP.${self:provider.stage}}

custom:
  suffix:
    prd: ""
    dev: -dev
  sourceIP:
    prd: 0.0.0.0/0
    dev: ${env:SOURCE_IP}/32
  customDomain:
    region: ap-northeast-1
    domainName: www${self:custom.suffix.${self:provider.stage}}.tojo.tokyo
    basePath: ''
    certificateName: "*.tojo.tokyo"
    stage: ${self:provider.stage}
    createRoute53Record: true

plugins:
  - serverless-domain-manager
