#lang aws-lambda-serverless
service: www-tojoqk-com

provider:
  name: aws
  runtime: provided
  region: ap-northeast-1
  memorySize: 512
  timeout: 5
  stage: ${env:STAGE}
  logRetentionInDays: 30
  resourcePolicy:
    - Effect: Allow
      Principal: "*"
      Action: execute-api:Invoke
      Resource:
        - execute-api:/*/*/*
      Condition:
        IpAddress:
          aws:SourceIp: ${self:custom.sourceIP.${self:provider.stage}}

custom:
  suffix:
    production: ""
    development: -dev
  sourceIP:
    production: 0.0.0.0/0
    development: ${env:SOURCE_IP}/32
  customDomain:
    region: ap-northeast-1
    domainName: www${self:custom.suffix.${self:provider.stage}}.tojoqk.com
    basePath: ''
    certificateName: "*.tojoqk.com"
    stage: ${self:provider.stage}
    createRoute53Record: true
  layer: arn:aws:lambda:ap-northeast-1:488514468674:layer:bootstrap:2

plugins:
  - serverless-domain-manager

package:
  exclude:
    - '*/**'
    - '.*/**'
  include:
    - bootstrap

functions:
  root:
    handler: main.root
    events:
      - http:
          method: get
          path: /
    layers:
      - ${self:custom.layer}
  home:
    handler: main.home
    events:
      - http:
          method: get
          path: "/home"
    layers:
      - ${self:custom.layer}
  about-me:
    handler: main.about-me
    events:
      - http:
          method: get
          path: "/about-me"
    layers:
      - ${self:custom.layer}
  game:
    handler: main.game
    events:
      - http:
          method: get
          path: "/game"
    layers:
      - ${self:custom.layer}
  not-found:
    handler: main.not-found
    events:
      - http:
          method: get
          path: "/{proxy+}"
    layers:
      - ${self:custom.layer}
